In [7]:
from IPython.display import Markdown, display
display(Markdown("# Introdução aos Word Vectors"))

display(Markdown("""
### Word Vectors (Vetores de Palavras) são representações numéricas de palavras, geralmente na forma de vetores de alta dimensionalidade. Eles são usados para capturar o significado de palavras com base no seu contexto em um espaço vetorial. Esses vetores permitem que algoritmos de aprendizado de máquina compreendam relações semânticas entre palavras.
"""))


# Introdução aos Word Vectors


### Word Vectors (Vetores de Palavras) são representações numéricas de palavras, geralmente na forma de vetores de alta dimensionalidade. Eles são usados para capturar o significado de palavras com base no seu contexto em um espaço vetorial. Esses vetores permitem que algoritmos de aprendizado de máquina compreendam relações semânticas entre palavras.


In [91]:
display(Markdown("""
### Os Word Vectors são fundamentais no campo do NLP porque permitem que máquinas compreendam e manipulem a linguagem de maneira mais semelhante ao humano.

### - **Representação semântica**: Capturam o significado das palavras com base em seu uso.
### - **Aplicações diversas**: Utilizados em tarefas como tradução automática, análise de sentimentos, e chatbots.
"""))


### Os Word Vectors são fundamentais no campo do NLP porque permitem que máquinas compreendam e manipulem a linguagem de maneira mais semelhante ao humano.

### - **Representação semântica**: Capturam o significado das palavras com base em seu uso.
### - **Aplicações diversas**: Utilizados em tarefas como tradução automática, análise de sentimentos, e chatbots.


In [92]:
display(Markdown("""
## Exemplos de Modelos de Word Vectors
### - **Word2Vec**: Um dos mais populares modelos para a criação de vetores de palavras, desenvolvido pelo Google.
### - **GloVe (Global Vectors)**: Modelo criado pela Stanford.
### - **FastText**: Desenvolvido pelo Facebook, é uma extensão do Word2Vec que trata palavras desconhecidas e derivadas (como plurais e conjugação).
"""))



## Exemplos de Modelos de Word Vectors
### - **Word2Vec**: Um dos mais populares modelos para a criação de vetores de palavras, desenvolvido pelo Google.
### - **GloVe (Global Vectors)**: Modelo criado pela Stanford.
### - **FastText**: Desenvolvido pelo Facebook, é uma extensão do Word2Vec que trata palavras desconhecidas e derivadas (como plurais e conjugação).


In [8]:
display(Markdown("""
## Como as Palavras são Representadas em Vetores
### - A representação de palavras em vetores é uma forma de converter palavras, que são entidades discretas, em uma forma que os algoritmos de aprendizado de máquina possam processar — essencialmente, números.

## 1. One-Hot Encoding
### - One-Hot Encoding é uma forma simples de representar palavras, mas não captura semântica.
"""))


## Como as Palavras são Representadas em Vetores
### - A representação de palavras em vetores é uma forma de converter palavras, que são entidades discretas, em uma forma que os algoritmos de aprendizado de máquina possam processar — essencialmente, números.

## 1. One-Hot Encoding
### - One-Hot Encoding é uma forma simples de representar palavras, mas não captura semântica.


In [1]:
# Exemplo de One-Hot Encoding com Sklearn
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Lista de palavras
palavras = [['homem'], ['mulher'], ['rainha'], ['rei']]

# Criando o One-Hot Encoder
one_hot_encoder = OneHotEncoder(sparse=False)
one_hot = one_hot_encoder.fit_transform(palavras)

# Exibindo as representações One-Hot
for palavra, vetor in zip(palavras, one_hot):
    print(f"Palavra: {palavra[0]} -----> One-Hot: {vetor}\n")

Palavra: homem -----> One-Hot: [1. 0. 0. 0.]

Palavra: mulher -----> One-Hot: [0. 1. 0. 0.]

Palavra: rainha -----> One-Hot: [0. 0. 1. 0.]

Palavra: rei -----> One-Hot: [0. 0. 0. 1.]



In [6]:
display(Markdown("""
## 2. Count Vectors
### - Conta a frequência de cada palavra em um corpus.
### - O CountVectorizer por padrão ignora palavras muito comuns, chamadas de "stop words" (como "o", "a", "de", etc.), porque elas geralmente não acrescentam significado importante em tarefas de processamento de linguagem natural.
"""))


## 2. Count Vectors
### - Conta a frequência de cada palavra em um corpus.
### - O CountVectorizer por padrão ignora palavras muito comuns, chamadas de "stop words" (como "o", "a", "de", etc.), porque elas geralmente não acrescentam significado importante em tarefas de processamento de linguagem natural.


In [11]:
# Exemplo de Count Vectors com Sklearn
from sklearn.feature_extraction.text import CountVectorizer

# Corpus de exemplo
corpus = [
    'o cachorro late',
    'o gato mia',
    'o cachorro mia',
]

# Criando o Count Vectorizer
vectorizer = CountVectorizer() 
X = vectorizer.fit_transform(corpus)

# Exibindo a representação das palavras
print("Vocabulário:", vectorizer.get_feature_names_out())
print("\nCount Vectors:\n", X.toarray())


Vocabulário: ['cachorro' 'gato' 'late' 'mia']

Count Vectors:
 [[1 0 1 0]
 [0 1 0 1]
 [1 0 0 1]]


In [17]:
display(Markdown("""
## TF-IDF (Term Frequency - Inverse Document Frequency)
### - Atribui pesos baseados na frequência das palavras, mas também ajusta os pesos através da raridade delas.
"""))


## TF-IDF (Term Frequency - Inverse Document Frequency)
### - Atribui pesos baseados na frequência das palavras, mas também ajusta os pesos através da raridade delas.


In [14]:
# Exemplo de TF-IDF com Sklearn
from sklearn.feature_extraction.text import TfidfVectorizer

# Corpus de exemplo
corpus = [
    'o cachorro late',
    'o gato mia',
    'o cachorro mia',
]

# Criando o TF-IDF Vectorizer
tfidf = TfidfVectorizer(smooth_idf=False)
X = tfidf.fit_transform(corpus)

# Exibindo a representação das palavras
print("Vocabulário:", tfidf.get_feature_names_out())
print("\nTF-IDF Vectors:\n", X.toarray())

Vocabulário: ['cachorro' 'gato' 'late' 'mia']

TF-IDF Vectors:
 [[0.55645052 0.         0.83088075 0.        ]
 [0.         0.83088075 0.         0.55645052]
 [0.70710678 0.         0.         0.70710678]]


In [13]:
display(Markdown("""
### - Frequência do Termo (TF) = Número de vezes que a palavra desejada aparece na frase / Número total de frases.
### - Frequência Inversa do Documento (IDF) = log ( Número total de frases / Número de documentos que contem a palvra desejada )
"""))


### - Frequência do Termo (TF) = Número de vezes que a palavra desejada aparece na frase / Número total de frases.
### - Frequência Inversa do Documento (IDF) = log ( Número total de frases / Número de documentos que contem a palvra desejada )


In [49]:
display(Markdown("""
## corpus = [
##    'o cachorro late',
##    'o gato mia',
##    'o cachorro mia'
## ]

### - TF(cachorro) = 1/3 = 0.333
### - IDF(cachorro) = log(3/2) ≈ 0.176

### - TF × IDF = 1/3 * log(3/2) = 0.05869708635 
"""))


## corpus = [
##    'o cachorro late',
##    'o gato mia',
##    'o cachorro mia'
## ]

### - TF(cachorro) = 1/3 = 0.333
### - IDF(cachorro) = log(3/2) ≈ 0.176

### - TF × IDF = 1/3 * log(3/2) = 0.05869708635 


In [16]:
display(Markdown("""
## O que é Bag of Words?
### - O Bag of Words é uma técnica simples para representar texto numericamente. Ele transforma um conjunto de documentos em uma matriz de frequências, onde cada linha representa um documento e cada coluna representa uma palavra do vocabulário total. 
"""))


## O que é Bag of Words?
### - O Bag of Words é uma técnica simples para representar texto numericamente. Ele transforma um conjunto de documentos em uma matriz de frequências, onde cada linha representa um documento e cada coluna representa uma palavra do vocabulário total. 


In [35]:
display(Markdown("""
## Construção do Vocabulário
### - Para construir o BoW, primeiro, precisamos identificar todas as palavras únicas (ou tokens) em um corpus de texto. Isso forma o vocabulário do modelo.
"""))


## Construção do Vocabulário
### - Para construir o BoW, primeiro, precisamos identificar todas as palavras únicas (ou tokens) em um corpus de texto. Isso forma o vocabulário do modelo.


In [17]:
# Exemplo prático - Construção do Vocabulário
from sklearn.feature_extraction.text import CountVectorizer  

# Lista de documentos de exemplo
corpus = [
    'O cachorro late alto',
    'O gato mia suavemente',
    'O cachorro e o gato estão juntos'
]

# Criando o modelo BoW
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

# Exibindo o vocabulário criado
print("Vocabulário:", vectorizer.get_feature_names_out())


Vocabulário: ['alto' 'cachorro' 'estão' 'gato' 'juntos' 'late' 'mia' 'suavemente']


In [34]:
display(Markdown("""
## Representação dos Documentos com Frequência de Palavras
### - Depois de construir o vocabulário, cada documento é representado como um vetor de frequências, onde cada posição no vetor indica o número de vezes que a palavra correspondente apareceu no documento..
"""))


## Representação dos Documentos com Frequência de Palavras
### - Depois de construir o vocabulário, cada documento é representado como um vetor de frequências, onde cada posição no vetor indica o número de vezes que a palavra correspondente apareceu no documento..


In [18]:
# Exemplo prático - Representação dos Documentos
# Convertendo os documentos para a matriz BoW
print("\nMatriz BoW:\n", X.toarray())



Matriz BoW:
 [[1 1 0 0 0 1 0 0]
 [0 0 0 1 0 0 1 1]
 [0 1 1 1 1 0 0 0]]


In [36]:
display(Markdown("""
## Pré-processamento do Texto:

### - Normalização: Muitas vezes, é útil normalizar o texto, como converter tudo para minúsculas ou remover pontuação.
### - Stop Words: Pode ser útil remover palavras comuns (como "o", "a", "e", etc.) que não agregam significado relevante.
### - Stemming/Lemmatization: Reduzir as palavras às suas raízes pode ajudar a reduzir a dimensionalidade do vocabulário. Ex: amigos para amig
"""))


## Pré-processamento do Texto:

### - Normalização: Muitas vezes, é útil normalizar o texto, como converter tudo para minúsculas ou remover pontuação.
### - Stop Words: Pode ser útil remover palavras comuns (como "o", "a", "e", etc.) que não agregam significado relevante.
### - Stemming/Lemmatization: Reduzir as palavras às suas raízes pode ajudar a reduzir a dimensionalidade do vocabulário. Ex: amigos para amig


In [37]:
display(Markdown("""
## Limitações do Bag of Words

### - Ignora a Ordem das Palavras: BoW não considera a ordem em que as palavras aparecem, o que pode resultar em perda de contexto.
### - Sparsidade da Matriz: A matriz resultante é frequentemente esparsa, com muitas posições zeradas, especialmente se o vocabulário for grande.
"""))


## Limitações do Bag of Words

### - Ignora a Ordem das Palavras: BoW não considera a ordem em que as palavras aparecem, o que pode resultar em perda de contexto.
### - Sparsidade da Matriz: A matriz resultante é frequentemente esparsa, com muitas posições zeradas, especialmente se o vocabulário for grande.


In [19]:
display(Markdown("""
## Exemplo de uso do Bag of words para análise de sentimentos
"""))


## Exemplo de uso do Bag of words para análise de sentimentos


In [28]:
# Importando bibliotecas necessárias
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Simulação de um dataset de reviews em português
corpus = [
    'Esse produto é excelente, adorei a qualidade',
    'Horrível, o produto chegou quebrado e não funciona',
    'Muito bom, chegou antes do prazo e funciona perfeitamente',
    'Produto ruim, não recomendo a ninguém',
    'Estou muito satisfeito com minha compra, voltarei a comprar aqui',
    'Péssima qualidade, não corresponde ao anunciado',
    'Maravilhoso, superou minhas expectativas',
    'O produto é frágil e não cumpre o prometido',
    'Nossa que produto bom, eu compraria muito mais deles',
    'Essa foi a pior coisa que eu comprei na minha vida, não recomendo'
]

# Rótulos: 1 = positivo, 0 = negativo
labels = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

# Transformando o corpus em Bag of Words
vectorizer = CountVectorizer() 
X = vectorizer.fit_transform(corpus)

print("\nVocabulário:", vectorizer.get_feature_names_out())
print("\nMatriz BoW:\n", X.toarray())

# Dividindo os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.4)

# Treinando o classificador Naive Bayes
clf = MultinomialNB()
clf.fit(X_train, y_train)

# Função para prever o sentimento de uma nova frase
def prever_sentimento(frase):
    frase_transformada = vectorizer.transform([frase])  # Transforma a frase usando o mesmo vectorizer
    predicao = clf.predict(frase_transformada)  # Faz a predição
    print("\nSaida do algoritimo:", predicao)
    return "Positivo" if predicao[0] == 1 else "Negativo"

# Exemplo de uso da função
nova_frase = "\nO produto é maravilhoso e funciona muito bem, muito mais do que eu esperava, estou satisfeito, compraria novamente"
resultado = prever_sentimento(nova_frase)
print("\nFrase:", nova_frase, " - Predição:", resultado)



Vocabulário: ['adorei' 'antes' 'anunciado' 'ao' 'aqui' 'bom' 'chegou' 'coisa' 'com'
 'compra' 'comprar' 'compraria' 'comprei' 'corresponde' 'cumpre' 'deles'
 'do' 'essa' 'esse' 'estou' 'eu' 'excelente' 'expectativas' 'foi' 'frágil'
 'funciona' 'horrível' 'mais' 'maravilhoso' 'minha' 'minhas' 'muito' 'na'
 'ninguém' 'nossa' 'não' 'perfeitamente' 'pior' 'prazo' 'produto'
 'prometido' 'péssima' 'qualidade' 'que' 'quebrado' 'recomendo' 'ruim'
 'satisfeito' 'superou' 'vida' 'voltarei']

Matriz BoW:
 [[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1
  0 0 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0
  1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
  0 0 0 1 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0

In [32]:
display(Markdown("""
## Word2Vec é uma técnica poderosa para gerar representações densas de palavras (word embeddings) que capturam relações semânticas e sintáticas entre palavras. Essas representações são amplamente utilizadas em diversas aplicações de Processamento de Linguagem Natural (NLP). Existem duas principais arquiteturas para treinar o Word2Vec:

### 1. **Continuous Bag of Words (CBOW)**: Prediz uma palavra alvo com base no contexto de palavras vizinhas.
### 2. **Skip-gram**: Prediz palavras de contexto com base em uma palavra alvo.
"""))


## Word2Vec é uma técnica poderosa para gerar representações densas de palavras (word embeddings) que capturam relações semânticas e sintáticas entre palavras. Essas representações são amplamente utilizadas em diversas aplicações de Processamento de Linguagem Natural (NLP). Existem duas principais arquiteturas para treinar o Word2Vec:

### 1. **Continuous Bag of Words (CBOW)**: Prediz uma palavra alvo com base no contexto de palavras vizinhas.
### 2. **Skip-gram**: Prediz palavras de contexto com base em uma palavra alvo.


In [8]:
display(Markdown("# Continuous Bag of Words (CBOW)"))
display(Markdown("""
### O CBOW tenta prever uma palavra alvo usando as palavras do contexto ao redor. Por exemplo, na frase "o cachorro está latindo", se a palavra alvo for "cachorro", o modelo CBOW tenta prever "cachorro" usando "o", "está", e "latindo".

## **Como Funciona:**
### 1. **Entrada**: Primeiro, representamos as palavras de contexto usando vetores One-Hot. Um vetor One-Hot é um vetor binário que possui um 1 na posição da palavra no vocabulário e 0 em todas as outras posições.

Vocabulário:

    "o" → [1, 0, 0, 0, 0]
    "cachorro" → [0, 1, 0, 0, 0]
    "está" → [0, 0, 1, 0, 0]
    "latindo" → [0, 0, 0, 1, 0]


Vetores de Contexto:

    "o" → [1, 0, 0, 0, 0]
    "está" → [0, 0, 1, 0, 0]
    "latindo" → [0, 0, 0, 1, 0]    

### 2. **Camada Oculta**: A camada oculta combina os vetores de contexto para formar uma representação do contexto. Normalmente, faz isso calculando a média dos vetores One-Hot.

### Cálculo da Média:
### h= 1/3 ( [1,0,0,0,0] + [0,0,1,0,0] + [0,0,0,1,0] )= [0.33,0,0.33,0.33,0]

### 3. **Saída**: Função de Saída: CBOW geralmente usa softmax na camada de saída.
### Como Funciona: CBOW prevê a palavra alvo usando as palavras de contexto ao redor. Por exemplo, na frase "o gato está dormindo", CBOW usaria as palavras "o", "está", e "dormindo" para prever "gato".
### Uso do Softmax: A função softmax é usada para calcular a probabilidade de cada palavra no vocabulário ser a palavra alvo, considerando o contexto. A softmax é aplicada na última camada da rede para transformar as pontuações dos embeddings em probabilidades, facilitando a previsão da palavra correta.

### Resumidante Softmax é usada para múltiplas classes, transformando um vetor de valores em probabilidades que somam 1.
"""))

# Continuous Bag of Words (CBOW)


### O CBOW tenta prever uma palavra alvo usando as palavras do contexto ao redor. Por exemplo, na frase "o cachorro está latindo", se a palavra alvo for "cachorro", o modelo CBOW tenta prever "cachorro" usando "o", "está", e "latindo".

## **Como Funciona:**
### 1. **Entrada**: Primeiro, representamos as palavras de contexto usando vetores One-Hot. Um vetor One-Hot é um vetor binário que possui um 1 na posição da palavra no vocabulário e 0 em todas as outras posições.

Vocabulário:

    "o" → [1, 0, 0, 0, 0]
    "cachorro" → [0, 1, 0, 0, 0]
    "está" → [0, 0, 1, 0, 0]
    "latindo" → [0, 0, 0, 1, 0]


Vetores de Contexto:

    "o" → [1, 0, 0, 0, 0]
    "está" → [0, 0, 1, 0, 0]
    "latindo" → [0, 0, 0, 1, 0]    

### 2. **Camada Oculta**: A camada oculta combina os vetores de contexto para formar uma representação do contexto. Normalmente, faz isso calculando a média dos vetores One-Hot.

### Cálculo da Média:
### h= 1/3 ( [1,0,0,0,0] + [0,0,1,0,0] + [0,0,0,1,0] )= [0.33,0,0.33,0.33,0]

### 3. **Saída**: Função de Saída: CBOW geralmente usa softmax na camada de saída.
### Como Funciona: CBOW prevê a palavra alvo usando as palavras de contexto ao redor. Por exemplo, na frase "o gato está dormindo", CBOW usaria as palavras "o", "está", e "dormindo" para prever "gato".
### Uso do Softmax: A função softmax é usada para calcular a probabilidade de cada palavra no vocabulário ser a palavra alvo, considerando o contexto. A softmax é aplicada na última camada da rede para transformar as pontuações dos embeddings em probabilidades, facilitando a previsão da palavra correta.

### Resumidante Softmax é usada para múltiplas classes, transformando um vetor de valores em probabilidades que somam 1.


In [28]:
# Importando a biblioteca necessária
from gensim.models import Word2Vec

# Corpus de exemplo
sentencas = [
    ['o', 'gato', 'está', 'dormindo'],
    ['o', 'cachorro', 'está', 'latindo'],
    ['o', 'passaro', 'está', 'cantando']
]

# Treinando o modelo CBOW
# sg=0 indica CBOW (se fosse sg=1, seria Skip-gram)
model_cbow = Word2Vec(sentencas, vector_size=10, window=2, min_count=1, sg=0, epochs=1000)

# Exibindo o vetor da palavra 'cachorro'
print("Vetor da palavra 'cachorro' usando CBOW:\n", model_cbow.wv['gato'])

# Predição: encontrando palavras similares à palavra 'cachorro'
similar_words = model_cbow.wv.most_similar(['o', 'está', 'dormindo'], topn=3)
print("\nPalavras mais similares a 'cachorro':", similar_words)

Vetor da palavra 'cachorro' usando CBOW:
 [-0.08801845  0.06749935 -0.04983679  0.02011902  0.06611765 -0.07721087
  0.08120681 -0.03733265 -0.08021297  0.07045902]

Palavras mais similares a 'cachorro': [('dormindo', 0.6484286785125732), ('cantando', 0.5246529579162598), ('gato', 0.4149939715862274)]


In [5]:
display(Markdown("# Skip-gram"))
display(Markdown("""
### O Skip-gram faz o oposto do CBOW: ele usa a palavra alvo para prever as palavras de contexto. Exemplo: Na frase "o gato está dormindo", a palavra "gato" é usada para prever "o", "está", e "dormindo".

## **Como Funciona:**
### 1. **Entrada**: Vetor One-Hot da palavra alvo.
### 2. **Camada Oculta**: Projeta o vetor da palavra alvo em um espaço de embedding.
### 3. **Saída**: Usa sigmoid e Negative Sampling para prever as palavras de contexto.
### 4. **Sigmoid** é ideal para previsões binárias e retorna uma probabilidade entre 0 e 1.

## Negative Sampling:
### Em vez de calcular o softmax sobre todas as palavras, o Skip-gram com Negative Sampling reduz o custo amostrando algumas "palavras negativas" que não estão no contexto.
"""))

# Skip-gram


### O Skip-gram faz o oposto do CBOW: ele usa a palavra alvo para prever as palavras de contexto. Exemplo: Na frase "o gato está dormindo", a palavra "gato" é usada para prever "o", "está", e "dormindo".

## **Como Funciona:**
### 1. **Entrada**: Vetor One-Hot da palavra alvo.
### 2. **Camada Oculta**: Projeta o vetor da palavra alvo em um espaço de embedding.
### 3. **Saída**: Usa sigmoid e Negative Sampling para prever as palavras de contexto.
### 4. **Sigmoid** é ideal para previsões binárias e retorna uma probabilidade entre 0 e 1.

## Negative Sampling:
### Em vez de calcular o softmax sobre todas as palavras, o Skip-gram com Negative Sampling reduz o custo amostrando algumas "palavras negativas" que não estão no contexto.


In [18]:
# Importando a biblioteca necessária
from gensim.models import Word2Vec

# Corpus de exemplo
sentencas = [
    ['o', 'gato', 'está', 'dormindo'],
    ['o', 'cachorro', 'está', 'latindo'],
    ['o', 'pássaro', 'está', 'cantando']
]

# Treinando o modelo Skip-gram
# sg=1 indica Skip-gram (se fosse sg=0, seria CBOW)
model_skipgram = Word2Vec(sentencas, vector_size=10, window=2, min_count=1, sg=1, epochs=1000)

# Exibindo o vetor da palavra 'cachorro'
print("Vetor da palavra 'cachorro' usando Skip-gram:\n", model_skipgram.wv['cachorro'])

# Predição: encontrando palavras similares à palavra 'gato'
similar_words_skipgram = model_skipgram.wv.most_similar('cachorro', topn=3)
print("\nPalavras mais similares a 'gato' usando Skip-gram:", similar_words_skipgram)


Vetor da palavra 'cachorro' usando Skip-gram:
 [-0.08384467  0.05030638 -0.04386335  0.01058092  0.08159344 -0.05159701
  0.05148339 -0.06023112 -0.04447963  0.09067195]

Palavras mais similares a 'gato' usando Skip-gram: [('latindo', 0.24998393654823303), ('pássaro', 0.10116135329008102), ('gato', 0.004566082265228033)]
